@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - List all\n the applications of a client and their state

autonumber

actor "Candidate" as Manager
participant ":System" as System

activate Manager

    Manager -> System : Asks to list their applications
    activate System
        System --> Manager : Provides a list of the Candidate's applications, \ntogether with their state and number of applicants.
    deactivate System

@enduml