-- Check the state of the customer
CREATE TRIGGER ANALYSISPHASE_TRIGGER
AFTER UPDATE ON T_ANALYSIS_PHASE
FOR EACH ROW
CALL "lapr4.jobs4u.TriggerDataSender";
CREATE TRIGGER APPLICATIONPHASE_TRIGGER
AFTER UPDATE ON T_APPLICATION_PHASE
FOR EACH ROW
CALL "lapr4.jobs4u.TriggerDataSender";
CREATE TRIGGER INTERVIEWPHASE_TRIGGER
AFTER UPDATE ON T_INTERVIEW_PHASE
FOR EACH ROW
CALL "lapr4.jobs4u.TriggerDataSender";
CREATE TRIGGER RESULTPHASE_TRIGGER
AFTER UPDATE ON T_RESULT_PHASE
FOR EACH ROW
CALL "lapr4.jobs4u.TriggerDataSender";
CREATE TRIGGER SCREENINGPHASE_TRIGGER
AFTER UPDATE ON T_SCREENING_PHASE
FOR EACH ROW
CALL "lapr4.jobs4u.TriggerDataSender";

-- Check application status
CREATE TRIGGER APPLICATIONRESULT_TRIGGER
AFTER UPDATE ON T_RESULT
FOR EACH ROW
CALL "lapr4.jobs4u.TriggerDataSender";

-- Check requirement result

CREATE TRIGGER REQUIREMENTRESULT_TRIGGER
AFTER UPDATE ON T_REQUIREMENT
FOR EACH ROW
CALL "lapr4.jobs4u.TriggerDataSender";

-- Check application insert
CREATE TRIGGER APPLICATIONINSERT_TRIGGER
AFTER INSERT ON T_APPLICATION
FOR EACH ROW
CALL "lapr4.jobs4u.TriggerDataSender";