@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Register Users

autonumber

actor "Admin" as Admin
participant ":System" as System

activate Admin

    Admin -> System : Asks to register an User of the Backoffice
    activate System

        System --> Admin : Asks for information (first name, last name, email, role)
        note left System : The Admin has to provide \nthe first and last name, the email and \nmust pick a role from the \nlist of available roles \n(Customer Manager, Operator and Language Engineer)

    deactivate System

    Admin -> System : Provides information
    activate System

        System --> Admin : Informs success or failure

    deactivate System

@enduml