@startuml CD-US1003

title Class Diagram - US1003

skinparam class {
    skinparam classAttributeIconSize 0
    skinparam packageStyle rectangle
    skinparam shadowing false
    skinparam linetype polyline
    BackgroundColor #FEF9E7
    ArrowColor Black
}

class "ListCandidateUI" as UI {}

class "CandidateController" as ListCandidateController {
    +allCandidates(): void
}

class "CandidateService" as CandidateService {
    +allJobOpenings(): Iterable<CandidateDTO>
}

class "Candidate" as Candidate {
    -name: string
    -email: Email
    +toDTO(): JobOpeningDTO
}

class "CandidateDTO" as CandidateDTO {
    +create(candidate: Candidate): CandidateDTO
}

class "CandidateRepository" as CandidateRepository {
    +findAll(): Iterable<JobOpening>
}

class "JpaCandidateRepository" as JpaCandidateRepository {
    +findAll(): Iterable<JobOpening>
}

class "Database" as DB <<(D, #8BEBFF)>> {}

UI --> ListCandidateController
ListCandidateController --> CandidateService
CandidateService --> Candidate
Candidate --> CandidateDTO
CandidateService --> CandidateRepository
CandidateRepository --> JpaCandidateRepository
JpaCandidateRepository --> DB

@enduml