@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - List all Candidates

autonumber

actor "Operator" as Manager
participant ":System" as System

activate Manager

    Manager -> System : Asks to list all candidates
    activate System

        note left of System : The system will show a list of candidates\n(US 2000a)


        System -> Manager : Shows list of candidates

    deactivate System
    
@enduml