@startuml

title Applications File Bot - Activity Diagram

start

partition Initialization {
  :Initialize system;
  :setupSignals();
  :getConfiguration();

}

partition NewFileCheckerProcess {
  fork
    :parent;
  fork again
    :newFileCheckerProcess;
    repeat
      :checkForNewFiles;
      if(newFilesDetected) then (yes)
        :sem_post(sem_newFiles);
      endif
      :sleep for n seconds;
    repeat while(NewFileCheckerProcess is running)
    end
  end fork
}

partition WorkerProcess {
  repeat
    fork
      :Parent;
    fork again
      :WorkerProcess;
      repeat
        :sem_wait(sem_startWorkers);
        :copyFiles;
        :sem_post(sem_startReport);
      repeat while(WorkerProcess is running)
      end
    end fork
  repeat while(for N processes)
}

partition ParentProcess {
  repeat
    :sem_wait(sem_newFiles);
    :listCandidatesIDs;
    while (There are candidates to send)
    :sem_post(sem_numberOfCandidates);
    endwhile
    repeat
      while(sem_trywait(sem_bufferSize) == 0)
      :sendWork();
      endwhile
      :sem_wait(reportFile);
      :reportFile();
      if(sem_trywait(sem_numberOfCandidates) == 1) then (yes)
        :break;
      endif
    repeat while(There are candidates to send)
  repeat while(System is running)
}

end

@enduml