@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - List all applications for a Job Opening

autonumber

actor "Operator" as Manager
participant ":System" as System

activate Manager

    Manager -> System : Asks to register a candidate and create the corresponding user
    activate System

     System -> Manager : request data of candidate

    deactivate System

    Manager -> System : inserts data (ie. email and name)
    activate System

        System -> Manager : shows operation success

    deactivate System
    
@enduml