@startuml CD-US1002

title Class Diagram - US1002

skinparam class {
    skinparam classAttributeIconSize 0
    skinparam packageStyle rectangle
    skinparam shadowing false
    skinparam linetype polyline
    BackgroundColor #FEF9E7
    ArrowColor Black
}

class "RegisterJobOpeningUI" as UI {}

class "RegisterJobOpeningController" as JobOpeningController {
    +addJobOpening(titleOrFunction: String, contractType: String, mode: String, address: String, company: String, numberOfVacancies: int, description: String): void
}

class "JobOpeningService" as JobOpeningService {
    +addJobOpening(titleOrFunction: String, contractType: String, mode: String, address: String, company: String, numberOfVacancies: int, description: String): JobOpening
}

class "JobOpening" as JobOpening {
    -titleOrFunction: String
    -contractType: String
    -mode: String
    -address: String
    -company: String
    -numberOfVacancies: int
    -description: String
    +createJobOpening(titleOrFunction: String, contractType: String, mode: String, address: String, company: String, numberOfVacancies: int, description: String): JobOpening
}

class "JobOpeningRepository" as JobOpeningRepository {
    +save(jobOpening: JobOpening): JobOpening
}

class "JpaJobOpeningRepository" as JpaJobOpeningRepository {
    +save(jobOpening: JobOpening): JobOpening
}

class "Database" as DB <<(D, #8BEBFF)>> {
}

UI --> JobOpeningController
JobOpeningController --> JobOpeningService
JobOpeningService --> JobOpening
JobOpeningService --> JobOpeningRepository
JobOpeningRepository --> JpaJobOpeningRepository
JpaJobOpeningRepository --> DB

@enduml