@startuml

skinparam classAttributeIconSize 0
hide empty attributes
hide empty methods
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

package "<<aggregate>> User" {

    entity User <<entity>> <<root>> {}

    class Email <<(V,#FF8B40) value object>> {}
    class FullName <<(V,#FF8B40) value object>> {}
    class Password <<(V,#FF8B40) value object>> {}
    class TaxPayerNumber <<(V,#FF8B40) value object>> {}
    class BirthDate <<(V,#FF8B40) value object>> {}
    class CreatedOn <<(V,#FF8B40) value object>> {}
    class Active <<(V,#FF8B40) value object>> {}
}

package "<<aggregate>> System Administrator" {
    entity Admin <<entity>> <<root>> {}
}

package "<<aggregate>> Customer Manager" {
    entity CustomerManager <<entity>> <<root>> {}
}

package "<<aggregate>> Operator" {
    entity Operator <<entity>> <<root>> {}
}

User --> "1" Email : characterized by
User --> "1" FullName : characterized by
User --> "1" Password : characterized by
User --> "1" TaxPayerNumber : characterized by
User --> "1" BirthDate : characterized by
User --> "1" CreatedOn : characterized by
User --> "1" Active : characterized by

Admin --> User
CustomerManager --> User
Operator --> User

@enduml