@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Enable Or Disable Users

autonumber

actor Operator
participant ":System" as System

activate Operator

    Operator -> System : Asks to generate a template file to help collect data
    activate System

        System --> Operator : Informs that the file was generated successfully
    deactivate System

    Operator -> System : Asks to export the template text file and specify the path
    activate System 
        System --> Operator : Informs that the file was exported successfully
    deactivate System

@enduml