@startuml SSD-US1004

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Edit a Job Opening.

autonumber

actor "Customer Manager" as CustomerManager
participant ":System" as System

activate CustomerManager

CustomerManager -> System : Asks to edit a job opening
activate System

System --> CustomerManager : Shows list of job openings
deactivate System

CustomerManager -> System : Chooses a job opening to edit
activate System

loop until the Customer Manager is satisfied with the changes
    System --> CustomerManager : Shows list of job opening attributes

    note right of CustomerManager : Attributes are: Title or function, Contract Type, Mode, Address,\nNumber of vacancies, Description, Requirement Specification, start and end date of the phases\ndepending on the phase that the recruitment process is in.

    CustomerManager -> System : Chooses an attribute to edit

    alt the chosen attribute is Recruitment Process
        System --> CustomerManager : Shows list of phases of the recruitment process
        CustomerManager -> System : Chooses a phase to edit
        System --> CustomerManager : Shows option to edit start and end date of the chosen phase
        CustomerManager -> System : Chooses an attribute to edit
    end
    
    System --> CustomerManager : Shows current value of chosen attribute and asks for new value

    CustomerManager -> System : Provides new value for chosen attribute
end

System --> CustomerManager : Asks to confirm changes
deactivate System

CustomerManager -> System : Confirms changes
activate System

System --> CustomerManager : Informs success or failure of update
deactivate System

deactivate CustomerManager

@enduml
