@startuml
title US1006b - SD - Display Candidate Data and Applications
skinparam linetype ortho
skinparam maxmessagesize 150
skinparam sequenceParticipant underline

actor "Customer Manager" as CM

participant "RegisterRankUI" as UI
participant "RegisterRankController" as C
participant "RankBuilder" as RB
participant "RankRepository" as RR
participant "JpaRankRepository" as JRR
database "Database" as DB




activate CM
    CM -> UI : Asks to display the personal data of a candidate
    activate UI
        ref over DB , CM: List Job Openings\n(US 1003)
            UI -> CM : Shows list of Job Openings and asks to select one
    deactivate UI
    CM -> UI : Selects a Job Opening
    activate UI
        ref over DB , CM: Get List of Applications for Job Opening\n(US 1005)
        loop for every application (until CM asks to stop)
        UI --> CM : Asks to select application for the rank nº[iteration of the loop]
    deactivate UI
        CM -> UI : Selects a candidate
        activate UI
            UI --> UI : saveToList(Application application)
        end loop

    loop for every candidate ranked
    UI --> C : setupRank(String rank Application application)
    activate C
        C -> C : registerRank(String rank, Application application)
        activate C
            C -> C : doSetupRank(String rank, Application application)
            activate C
                C -> RB : createRank(String rank, Application application)
                activate RB
                    RB --> C : rank
                deactivate RB
                C --> C : rank
            deactivate C
            C -> RR : registerRank(Rank rank)

            activate RR
                RR -> JRR : save(Rank)
                activate JRR
                    JRR -> DB : persist(rank)
                    activate DB
                        DB --> JRR : rank
                    deactivate DB
                    JRR --> RR : rank
                deactivate JRR
                RR --> C : rank
            deactivate RR
            C --> C : rank
            deactivate C
        C --> UI : rank
    deactivate C
    end loop
    UI --> CM : Show operation success
deactivate CM

@enduml