@startuml SD-US1007

title Sequence Diagram - US1007: Setting Up Recruitment Phases

skinparam linetype ortho
skinparam maxmessagesize 150
skinparam sequenceParticipant underline

actor "Customer Manager" as customerManager

participant "SetUpRecruitmentProcessUI" as UI
participant "SetUpRecruitmentProcessController" as SetUpRecruitmentProcessController
participant "RecruitmentProcessService" as RecruitmentProcessService
participant "RecruitmentProcessFactory" as RecruitmentProcessFactory
participant "RecruitmentProcessRepository" as RecruitmentProcessRepository
participant "JpaRecruitmentProcessRepository" as JpaRecruitmentProcessRepository
database "Database" as DB

activate customerManager
    customerManager -> UI : Asks to setup the phases of the process for a job opening
    activate UI
        ref over customerManager, DB : US1003 ➡️ List Job Openings
        UI --> customerManager : Shows list of job openings and asks to select one
    deactivate UI
        customerManager -> UI : Selects job opening to setup the phases
    activate UI
        loop for each phase
            alt phase is "Application"
                UI --> customerManager : Asks for information (initial date and final date)
                customerManager -> UI : Provides information
                UI -> SetUpRecruitmentProcessController : createApplicationPhase(initialDate, finalDate)
                activate SetUpRecruitmentProcessController
                    SetUpRecruitmentProcessController -> RecruitmentProcessService : createApplicationPhase(initialDate, finalDate)
                activate RecruitmentProcessService
                    RecruitmentProcessService -> RecruitmentProcessFactory : createApplicationPhase(initialDate, finalDate)
                    activate RecruitmentProcessFactory
                        RecruitmentProcessFactory --> RecruitmentProcessService : phase
                    deactivate RecruitmentProcessFactory
                    RecruitmentProcessService --> SetUpRecruitmentProcessController : phase
                deactivate RecruitmentProcessService
            else phase is "Screening"
                UI --> customerManager : Asks for information (initial date and final date)
                customerManager -> UI : Provides information
                UI -> SetUpRecruitmentProcessController : createScreeningPhase(initialDate, finalDate)
                SetUpRecruitmentProcessController -> RecruitmentProcessService : createScreeningPhase(initialDate, finalDate)
                activate RecruitmentProcessService
                    RecruitmentProcessService -> RecruitmentProcessFactory : createScreeningPhase(initialDate, finalDate)
                    activate RecruitmentProcessFactory
                        RecruitmentProcessFactory --> RecruitmentProcessService : phase
                    deactivate RecruitmentProcessFactory
                    RecruitmentProcessService --> SetUpRecruitmentProcessController : phase
                deactivate RecruitmentProcessService
            else phase is "Interview"
                UI --> customerManager : Asks if the interview phase is needed
                customerManager -> UI : Responds (y/n)
                alt response is "y"
                    UI --> customerManager : Asks for information (initial date and final date)
                    customerManager -> UI : Provides information
                    UI -> SetUpRecruitmentProcessController : createInterviewPhase(initialDate, finalDate)
                    SetUpRecruitmentProcessController -> RecruitmentProcessService : createInterviewPhase(initialDate, finalDate)
                    activate RecruitmentProcessService
                        RecruitmentProcessService -> RecruitmentProcessFactory : createInterviewPhase(initialDate, finalDate)
                        activate RecruitmentProcessFactory
                            RecruitmentProcessFactory --> RecruitmentProcessService : phase
                        deactivate RecruitmentProcessFactory
                        RecruitmentProcessService --> SetUpRecruitmentProcessController : phase
                    deactivate RecruitmentProcessService
                end
            else phase is "Analysis"
                UI --> customerManager : Asks for information (initial date and final date)
                customerManager -> UI : Provides information
                UI -> SetUpRecruitmentProcessController : createAnalysisPhase(initialDate, finalDate)
                SetUpRecruitmentProcessController -> RecruitmentProcessService : createAnalysisPhase(initialDate, finalDate)
                activate RecruitmentProcessService
                    RecruitmentProcessService -> RecruitmentProcessFactory : createAnalysisPhase(initialDate, finalDate)
                    activate RecruitmentProcessFactory
                        RecruitmentProcessFactory --> RecruitmentProcessService : phase
                    deactivate RecruitmentProcessFactory
                    RecruitmentProcessService --> SetUpRecruitmentProcessController : phase
                deactivate RecruitmentProcessService
            else phase is "Result"
                UI --> customerManager : Asks for information (initial date and final date)
                customerManager -> UI : Provides information
                UI -> SetUpRecruitmentProcessController : createResultPhase(initialDate, finalDate)
                SetUpRecruitmentProcessController -> RecruitmentProcessService : createResultPhase(initialDate, finalDate)
                activate RecruitmentProcessService
                    RecruitmentProcessService -> RecruitmentProcessFactory : createResultPhase(initialDate, finalDate)
                    activate RecruitmentProcessFactory
                        RecruitmentProcessFactory --> RecruitmentProcessService : phase
                    deactivate RecruitmentProcessFactory
                    RecruitmentProcessService --> SetUpRecruitmentProcessController : phase
                deactivate RecruitmentProcessService
            end
        end
        alt all phases were created
            activate SetUpRecruitmentProcessController
            SetUpRecruitmentProcessController -> RecruitmentProcessFactory : createRecruitmentProcess(ApplicationPhase, ScreeningPhase, InterviewPhase, AnalysisPhase, ResultPhase)
            activate RecruitmentProcessFactory
                RecruitmentProcessFactory --> SetUpRecruitmentProcessController : recruitmentProcess
            deactivate RecruitmentProcessFactory
        else "Interview" phase was not created
            SetUpRecruitmentProcessController -> RecruitmentProcessFactory : createRecruitmentProcess(ApplicationPhase, ScreeningPhase, AnalysisPhase, ResultPhase)
            activate RecruitmentProcessFactory
                RecruitmentProcessFactory --> SetUpRecruitmentProcessController : recruitmentProcess
            deactivate RecruitmentProcessFactory
        end
        SetUpRecruitmentProcessController -> RecruitmentProcessService : save(recruitmentProcess)
        activate RecruitmentProcessService
            RecruitmentProcessService -> RecruitmentProcessRepository : save(recruitmentProcess)
        activate RecruitmentProcessRepository
            RecruitmentProcessRepository -> JpaRecruitmentProcessRepository : save(recruitmentProcess)
            activate JpaRecruitmentProcessRepository
                JpaRecruitmentProcessRepository -> DB : persist(recruitmentProcess)
                activate DB
                    DB --> JpaRecruitmentProcessRepository :  recruitmentProcess
                deactivate DB
                JpaRecruitmentProcessRepository --> RecruitmentProcessRepository :  recruitmentProcess
            deactivate JpaRecruitmentProcessRepository
            RecruitmentProcessRepository --> RecruitmentProcessService :  recruitmentProcess
        deactivate RecruitmentProcessRepository
            RecruitmentProcessService --> SetUpRecruitmentProcessController :  recruitmentProcess
        deactivate RecruitmentProcessService
        SetUpRecruitmentProcessController --> UI : recruitmentProcess
    deactivate SetUpRecruitmentProcessController
    UI --> customerManager : Informs success or failure
    deactivate UI
deactivate customerManager

@enduml