@startuml SSD-US1003
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - List Job Openings

autonumber

actor "Customer Manager" as Manager
participant ":System" as System

activate Manager

Manager -> System : Asks for a list of job openings
activate System
    System --> Manager : Displays list of job openings and provides a filtering option
deactivate System

note left of System : By default, the system displays all job openings \nassociated with the customer manager without filters.

opt Optionally applies filters
    loop While there are filters to apply
        Manager -> System : Asks to filter the list of job openings
        activate System
            System --> Manager : Displays the filter options
        deactivate System
        note left of System : The System should display the state \nof each filter (active or not).
        alt "Filter by active status"
            Manager -> System : Inputs active status filter criteria
            activate System
        else "Filter by customer"
            Manager -> System : Inputs customer filter criteria
        else "Filter by date"
            Manager -> System : Inputs date filter criteria
        end
        System --> Manager : Displays the filtered list of job openings
        deactivate System
    end    
end

@enduml
