@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Register Job Openings

autonumber

actor "Customer Manager" as Manager
participant ":System" as System

activate Manager

    Manager -> System : Asks to register job opening
    activate System
        
        System --> Manager : Asks for what Customer the job opening is
    
    deactivate System

    Manager -> System : Provides company

        System --> Manager : Asks for information (Title or function, Contract Type, Mode, Address, Number of vacancies, Description)
            note left System : The Costumer Manager has to provide \nall the information required

    deactivate System

    Manager -> System : Provides information
    activate System

        System --> Manager : Asks to select one of the requirements
        ref over System, Manager : US1009 ➡️ Select Requirement

    deactivate System

    Manager -> System : Selects one of the requirements
    activate System

        System --> Manager : Informs success or failure

@enduml