@startuml

title Class Diagram - US1014

skinparam class {
    skinparam classAttributeIconSize 0
    skinparam packageStyle rectangle
    skinparam shadowing false
    skinparam linetype polyline
    BackgroundColor #FEF9E7
    ArrowColor Black
}

class "DisplayDataUI" as UI {}

class "DisplayDataController" as Controller {
    +getApplicationRequirementFile(Application):Requirement
    +getApplicationInterviewFile(Application):Interview
}

class "Database" as DB <<(D, #8BEBFF)>> {
}

class RequirementRepository <<(R, #FFFF99)>>{
    +findRequirement(application):Requirement
}

class JpaRequirementsRepository <<(R, #FFFF99)>>{
    +findRequirement(application):Requirement
}
class InterviewRepository <<(R, #FFFF99)>>{
    +findInterviewByApplication(interview):Interview
}

class JpaInterviewRepository <<(R, #FFFF99)>>{
    +findInterviewByApplication(interview):Interview
}
class ListApplicationDataService <<(S, #90EE90)>>{
    +findApplicationRequirementfile : Requirement
    +findInterviewByApplication :Interview
}


UI --> Controller

'Controller

Controller --> RequirementRepository
Controller --> ListApplicationDataService
Controller --> InterviewRepository


'Repository
RequirementRepository --> JpaRequirementsRepository
JpaRequirementsRepository --> DB
InterviewRepository --> JpaInterviewRepository
JpaInterviewRepository --> DB


@enduml