@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram (SD) - Displayes all data of an application

autonumber

actor "Customer Manager" as Manager
participant "DisplayDataApplicationUI" as UI
participant "DisplayDataApplicationController" as Controller
participant "DisplayDataApplicationJPA" as jpa
database "Database" as DB
activate Manager

    Manager -> UI : Asks to register display all the data of an application
    activate UI

    ref over UI : List job openings \n(US 1003)
 UI -> Manager : displays list of job openings and asks to choose of which the application belongs to

    deactivate UI

    Manager -> UI : selects one job opening
    activate UI
            ref over UI : List applications for a job opening \n(US 1005)

        UI -> Manager : dysplayes list of applications for the job opening

deactivate UI

     Manager -> UI : selects an application


    activate UI

    UI -> Controller : getApplicationData(application)

    activate Controller

    Controller -> jpa : getApplicationData(application)

    activate jpa

    jpa -> DB : getApplicationData(application)

    activate DB

    DB -> jpa : applicationData

    deactivate DB

    jpa -> Controller : applicationData

    deactivate jpa

    Controller -> UI : applicationData

    deactivate Controller

        UI -> Manager : dysplayes all data of the application

    deactivate UI
    
@enduml